#
# Copyright (c) 2022-present, IO Visor Project
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Windows

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

      build_type:
        required: true
        type: string

      upload_packages:
        required: true
        type: boolean

      build_codeql:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Initialize CodeQL
      if: inputs.build_codeql == true
      uses: github/codeql-action/init@807578363a7869ca324a79039e6db9c843e0e100
      with:
        languages: 'cpp'

    - name: Configure uBPF
      run: |
        cmake `
          -S . `
          -B build `
          -DUBPF_ENABLE_TESTS=true `
          -DUBPF_ENABLE_INSTALL=true

    - name: Build uBPF
      run: |
        cmake `
          --build build `
          --config ${{ inputs.build_type }}

    # Switch this to Docker when a Windows image is available.
    - name: Run the bpf_conformance tests (Windows)
      run: |
        cd .\build\bin\${{ inputs.build_type }}
        .\bpf_conformance_runner.exe --test_file_directory ..\tests --plugin_path ubpf_plugin.exe --plugin_options --jit
        .\bpf_conformance_runner.exe --test_file_directory ..\tests --plugin_path ubpf_plugin.exe --plugin_options --interpret

    - name: Generate the TGZ package
      run: |
        cmake `
          -S . `
          -B build `
          -DUBPF_ENABLE_PACKAGE=true `
          -DCPACK_GENERATOR=TGZ

        cmake `
          --build build `
          --target package

    - name: Locate the packages
      id: package_locations
      if: inputs.upload_packages == true
      shell: bash
      run: |
        echo ::set-output name=REL_TGZ_PACKAGE_PATH::$(ls build/*.tar.gz)

    - name: Upload the Windows TGZ package
      if: inputs.upload_packages == true
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      with:
        name: windows_tgz_package
        path: ${{ steps.package_locations.outputs.REL_TGZ_PACKAGE_PATH }}
        retention-days: 5

    - name: Perform CodeQL Analysis
      if: inputs.build_codeql == true
      uses: github/codeql-action/analyze@807578363a7869ca324a79039e6db9c843e0e100